# Generated by Django 4.0.1 on 2022-01-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_artists_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='art_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_name', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=100)),
                ('C_address', models.TextField()),
                ('C_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paintings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Style', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('Desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_date', models.DateField()),
                ('P_bill', models.IntegerField()),
                ('P_type', models.CharField(max_length=100)),
                ('P_desc', models.TextField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.customer')),
                ('Paintings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.paintings')),
            ],
        ),
        migrations.AddField(
            model_name='paintings',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ord_type', models.CharField(max_length=100)),
                ('Ord_no', models.IntegerField()),
                ('Ord_desc', models.TextField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.customer')),
                ('Paintings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.paintings')),
            ],
        ),
        migrations.CreateModel(
            name='exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=100)),
                ('E_type', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('G_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.art_gallery')),
            ],
        ),
    ]
