# Generated by Django 4.0.1 on 2022-01-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_art_gallery_customer_paintings_artist_image_payment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paintings',
            new_name='painting',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='C_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
