# Generated by Django 4.0.1 on 2022-01-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_g_name_art_gallery_gallery_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='Style',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='Year',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='Genre',
        ),
    ]
