# Generated by Django 4.0.1 on 2022-01-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_gallery',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
