# Generated by Django 4.0.1 on 2022-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_art_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_gallery',
            name='Desc',
        ),
        migrations.AddField(
            model_name='art_gallery',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
