# Generated by Django 4.0.1 on 2022-01-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_art_gallery_desc_art_gallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Paintings',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
