# Generated by Django 4.0.1 on 2022-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_payment_customer_remove_payment_paintings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='Gallery_ID',
        ),
        migrations.DeleteModel(
            name='art_gallery',
        ),
        migrations.DeleteModel(
            name='exhibition',
        ),
    ]
